version: '3.9'
services:
  mongodb:
    image: mongo
    container_name: mongo_container
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: postech
    networks:
      - my_network

  app:
    build: .
    container_name: postech_customer_container
    ports:
      - 3001:3001
    environment:
      - DB_HOST=mongodb
      - DB_PORT=27017
      - DB_USER=root
      - DB_PASS=postech
      - DB_NAME=postech_custumer
    volumes:
      - .:/usr/app
    depends_on:
      - mongodb
    networks:
      - my_network

networks:
  my_network:
