version: '3.9'
services:
  app:
    build: .
    container_name: postech_customer_container
    ports:
      - 3001:3001
    environment:
      - DB_HOST=fiap-customer.zkrx8sl.mongodb.net
      - DB_PORT=27017
      - DB_USER=root
      - DB_PASS=postech
      - DB_NAME=fiap-customer
    volumes:
      - .:/usr/app
    networks:
      - fiap-network

networks:
  fiap-network:
    external: true
