version: '3.9'
services:
  app:
    build: .
    container_name: postech_customer_container
    ports:
      - 3001:3001
    environment:
      - DB_HOST=postech.ufjbi3d.mongodb.net
      - DB_PORT=27017
      - DB_USER=root
      - DB_PASS=postech
      - DB_NAME=postech_custumer
    volumes:
      - .:/usr/app
    networks:
      - my_network

networks:
  my_network:
    external: true
