version: '3.9'
services:
  app:
    build: .
    container_name: postech_payment_container
    ports:
      - 3002:3002
    environment:
      - ML_PUBLIC_KEY=TEST-580c0533-1d6b-4cd6-a936-42b0051102df
      - ML_ACCESS_TOKEN=TEST-7456580585039188-012819-455f57e3f99cb1ca44c09a1ac2373791-304069289
    volumes:
      - .:/usr/app
    networks:
      - fiap-network

networks:
  fiap-network:
    external: true
