version: '3.9'

services:
  database:
    image: postgres
    container_name: database_postech
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postech
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: postech
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
