apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        env:
          - name: POSTGRES_USER
            value: root
          - name: POSTGRES_PASSWORD
            value: "root"
          - name: POSTGRES_DB
            value: postech
        ports:
        - containerPort: 5432
        resources:   
          requests:
            memory: "64Mi"   # Mem칩ria inicial / MI = milicores (1 core = 1000 milicores)
            cpu: "50m"       # CPU inicial 
          limits:
            memory: "128Mi"  # Limite m치ximo de mem칩ria
            cpu: "500m"      # Limite m치ximo de CPU  / M = megabytes
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30001  
  type: NodePort
